#!/usr/bin/python
# encoding: utf-8

def build_test_program(bld, name):
    test = bld.new_task_gen('cc', 'program')
    test.source = name + '.vala'
    test.uselib_local = 'desktop-agnostic'
    test.vapi_dirs = '../libdesktop-agnostic'
    #test.threading = True
    test.includes = '..'
    test.target = name
    test.install_path = ''

def build(bld):
    [build_test_program(bld, 'test-' + name)
     for name in ['color', 'config-bridge', 'desktop-entry', 'vfs-file',
                  'vfs-file-monitor', 'vfs-glob', 'vfs-trash', 'vfs-volume']]
