#! /usr/bin/env python
# encoding: utf-8

deps = {
    'cfg': {
        'gconf': {
            'uselib': 'GCONF',
            'packages': 'gconf-2.0'
        }
    }
}

def task_module(type_name, src_prefix):
    def build_module(bld, name):
        module = bld.new_task_gen('cc', 'shlib')
        module.source = '%s-%s.vala' % (src_prefix, name)
        if type_name in deps and name in deps[type_name]:
            module.uselib = deps[type_name][name]['uselib']
            module.packages = deps[type_name][name]['packages']
        module.uselib_local = 'desktop-agnostic'
        module.target = 'da-%s-%s' % (type_name, name)
        module.vapi_dirs = '../vapi'
        module.includes = '..'
        module.install_path = None
        bld.install_files('${LIBDIR}/desktop-agnostic/modules',
                          bld.env['shlib_PATTERN'] % module.target)
    return build_module

def set_options(opt):
    opt.add_option('--config-backends', type='string',
                   help='Determines which configuration backend(s) will be built.',
                   dest='config_backends', default='')

def build(bld):
    lib = bld.new_task_gen('cc', 'shlib')
    lib.source = ' '.join([
        'color.vala',
        'config-iface.vala',
        'config-bridge.vala',
        'config-schema.vala',
        'config-schema-option.vala',
        'config-schema-type.vala',
        'module.vala',
        'vfs-glob.vala'
        ])
    lib.packages = 'gdk-2.0 gmodule-2.0'
    lib.target = 'desktop-agnostic'
    lib.uselib = 'GDK GMODULE'
    lib.packages_private = 'posix-glob posix-errno'
    lib.vapi_dirs = '../vapi'
    lib.includes='..'

    [task_module('cfg', 'config-impl')(bld, name)
     for name in bld.env['BACKENDS_CFG']]
    [task_module('cfg-type', 'config-type')(bld, name)
     for name in ['color']]
