#!/usr/bin/env python
# encoding: utf-8

import misc

def build(bld):
    pc = bld.new_task_gen('subst')
    pc.source = 'desktop-agnostic.pc.in'
    pc.target = 'desktop-agnostic.pc'
    pc.dict = {
        'API_VERSION': bld.env['API_VERSION'],
        'LIBDIR': bld.env['LIBDIR'],
        'VERSION': bld.env['VERSION'],
        'prefix': bld.env['PREFIX'],
        'datarootdir': bld.env['DATADIR']
        }
    pc.fun = misc.subst_func
    pc.install_path = '${LIBDIR}/pkgconfig'
