#!/usr/bin/python
# encoding: utf-8


def build(bld):
    if 'gconf' in bld.env['BACKENDS_CFG']:
        schema = bld.new_task_gen('cc', 'program')
        schema.source = 'lda-schema-to-gconf.vala'
        schema.uselib_local = 'desktop-agnostic-cfg'
        schema.vapi_dirs = '../libdesktop-agnostic'
        schema.target = 'lda-schema-to-gconf'
    launcher = bld.new_task_gen('cc', 'program')
    launcher.source = 'lda-desktop-entry-editor.vala'
    launcher.packages = 'desktop-agnostic-ui'
    launcher.packages_private = 'build'
    launcher.uselib_local = 'desktop-agnostic-ui'
    launcher.vapi_dirs = '../libdesktop-agnostic ../vapi'
    launcher.target = 'lda-desktop-entry-editor'
